// <auto-generated />
using System;
using DesafioMirante.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioMirante.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContextoAplicacao))]
    partial class ContextoAplicacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("DesafioMirante.Domain.Entities.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcluidoPor")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskComments", (string)null);
                });

            modelBuilder.Entity("DesafioMirante.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcluidoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioResponsavelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Titulo");

                    b.HasIndex("UsuarioResponsavelId");

                    b.HasIndex("Status", "Prioridade");

                    b.ToTable("TaskItems", (string)null);
                });

            modelBuilder.Entity("DesafioMirante.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcluidoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DesafioMirante.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("DesafioMirante.Domain.Entities.User", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DesafioMirante.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Comentarios")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("DesafioMirante.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("DesafioMirante.Domain.Entities.User", "UsuarioResponsavel")
                        .WithMany("TarefasResponsaveis")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("DesafioMirante.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("DesafioMirante.Domain.Entities.User", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("TarefasResponsaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
